class Stall:
    def __init__(self, id: str, theme: str, misc: bool) -> None:
        self.id = id
        self.theme = theme
        self.misc = misc
        pass

    pass


class Route:
    def __init__(self, id: str, sequence: list[str], weight: float) -> None:
        self.id = id
        self.sequence = sequence
        self.weight = weight
        pass

    pass


class Hall:
    def __init__(self, id: str, theme: str, stalls: list[Stall]) -> None:
        self.id = id
        self.theme = theme
        self.stalls = stalls
        pass

    pass


HALLS = {
    "H1": Hall(
        "H1",
        "Cutting",
        [
            Stall("H1_1", "Cutting", False),
            Stall("H1_2", "Cutting", False),
            Stall("H1_3", "Pressing", False),
            Stall("H1_4", "Cutting", False),
            Stall("H1_5", "Lasers", False),
            Stall("H1_6", "Cutting", False),
            Stall("H1_7", "Software", True),
            Stall("H1_8", "Cutting", False),
            Stall("H1_9", "Cutting", False),
            Stall("H1_10", "Services", False),
            Stall("H1_11", "Cutting", False),
            Stall("H1_12", "Automation", False),
            Stall("H1_13", "Cutting", False),
            Stall("H1_14", "Media", True),
            Stall("H1_15", "Cutting", False),
            Stall("H1_16", "Cutting", False),
            Stall("H1_17", "Cutting", False),
            Stall("H1_18", "Cutting", False),
            Stall("H1_19", "Pipes", False),
            Stall("H1_20", "Cutting", False),
            Stall("H1_21", "Cutting", False),
            Stall("H1_A", "Cutting", False),
            Stall("H1_B", "Cutting", False),
            Stall("H1_C", "Cutting", False),
            Stall("H1_D", "Cutting", False),
        ],
    ),
    "H2": Hall(
        "H2",
        "Pressing",
        [
            Stall("H2_1", "Pressing", False),
            Stall("H2_2", "Cutting", False),
            Stall("H2_3", "Pressing", False),
            Stall("H2_4", "Lasers", False),
            Stall("H2_5", "Pressing", False),
            Stall("H2_6", "Lighting", True),
            Stall("H2_7", "Pressing", False),
            Stall("H2_8", "Automation", False),
            Stall("H2_9", "Pressing", False),
            Stall("H2_10", "Services", False),
            Stall("H2_11", "Pressing", False),
            Stall("H2_12", "Pressing", False),
            Stall("H2_13", "Fasteners", False),
            Stall("H2_14", "Pressing", False),
            Stall("H2_15", "Media", True),
            Stall("H2_16", "Pressing", False),
            Stall("H2_17", "Pressing", False),
            Stall("H2_18", "Pressing", False),
            Stall("H2_19", "Pressing", False),
            Stall("H2_20", "Tools", False),
            Stall("H2_21", "Pressing", False),
            Stall("H2_A", "Pressing", False),
            Stall("H2_B", "Pressing", False),
            Stall("H2_C", "Pressing", False),
            Stall("H2_D", "Pressing", False),
        ],
    ),
    "H3": Hall(
        "H3",
        "Lasers",
        [
            Stall("H3_1", "Lasers", False),
            Stall("H3_2", "Automation", False),
            Stall("H3_3", "Lasers", False),
            Stall("H3_4", "Cutting", False),
            Stall("H3_5", "Lasers", False),
            Stall("H3_6", "Software", True),
            Stall("H3_7", "Lasers", False),
            Stall("H3_8", "Pipes", False),
            Stall("H3_9", "Lasers", False),
            Stall("H3_10", "Media", True),
            Stall("H3_11", "Lasers", False),
            Stall("H3_12", "Pressing", False),
            Stall("H3_13", "Lasers", False),
            Stall("H3_14", "Services", True),
            Stall("H3_15", "Lasers", False),
            Stall("H3_16", "Lasers", False),
            Stall("H3_17", "Fasteners", False),
            Stall("H3_18", "Lasers", False),
            Stall("H3_19", "Lasers", False),
            Stall("H3_20", "Lasers", False),
            Stall("H3_21", "Lasers", False),
            Stall("H3_A", "Lasers", False),
            Stall("H3_B", "Lasers", False),
            Stall("H3_C", "Lasers", False),
            Stall("H3_D", "Lasers", False),
        ],
    ),
    "H4": Hall(
        "H4",
        "Pipes",
        [
            Stall("H4_1", "Pipes", False),
            Stall("H4_2", "Cutting", False),
            Stall("H4_3", "Pipes", False),
            Stall("H4_4", "Automation", False),
            Stall("H4_5", "Pipes", False),
            Stall("H4_6", "Software", True),
            Stall("H4_7", "Pipes", False),
            Stall("H4_8", "Fasteners", False),
            Stall("H4_9", "Pipes", False),
            Stall("H4_10", "Lighting", True),
            Stall("H4_11", "Pipes", False),
            Stall("H4_12", "Pressing", False),
            Stall("H4_13", "Pipes", False),
            Stall("H4_14", "Services", True),
            Stall("H4_15", "Pipes", False),
            Stall("H4_16", "Lasers", False),
            Stall("H4_17", "Pipes", False),
            Stall("H4_18", "Pipes", False),
            Stall("H4_19", "Pipes", False),
            Stall("H4_20", "Pipes", False),
            Stall("H4_21", "Pipes", False),
            Stall("H4_A", "Pipes", False),
            Stall("H4_B", "Pipes", False),
            Stall("H4_C", "Pipes", False),
            Stall("H4_D", "Pipes", False),
        ],
    ),
    "H5": Hall(
        "H5",
        "Fasteners",
        [
            Stall("H5_1", "Fasteners", False),
            Stall("H5_2", "Tools", False),
            Stall("H5_3", "Fasteners", False),
            Stall("H5_4", "Automation", False),
            Stall("H5_5", "Fasteners", False),
            Stall("H5_6", "Media", True),
            Stall("H5_7", "Fasteners", False),
            Stall("H5_8", "Cutting", False),
            Stall("H5_9", "Fasteners", False),
            Stall("H5_10", "Software", True),
            Stall("H5_11", "Fasteners", False),
            Stall("H5_12", "Pressing", False),
            Stall("H5_13", "Fasteners", False),
            Stall("H5_14", "Services", False),
            Stall("H5_15", "Fasteners", False),
            Stall("H5_16", "Lasers", False),
            Stall("H5_17", "Fasteners", False),
            Stall("H5_18", "Fasteners", False),
            Stall("H5_19", "Fasteners", False),
            Stall("H5_20", "Fasteners", False),
            Stall("H5_21", "Fasteners", False),
            Stall("H5_A", "Fasteners", False),
            Stall("H5_B", "Fasteners", False),
            Stall("H5_C", "Fasteners", False),
            Stall("H5_D", "Fasteners", False),
        ],
    ),
    "H6": Hall(
        "H6",
        "Automation",
        [
            Stall("H6_1", "Automation", False),
            Stall("H6_2", "Cutting", False),
            Stall("H6_3", "Automation", False),
            Stall("H6_4", "Pressing", False),
            Stall("H6_5", "Automation", False),
            Stall("H6_6", "Services", True),
            Stall("H6_7", "Automation", False),
            Stall("H6_8", "Tools", False),
            Stall("H6_9", "Automation", False),
            Stall("H6_10", "Software", True),
            Stall("H6_11", "Automation", False),
            Stall("H6_12", "Lasers", False),
            Stall("H6_13", "Automation", False),
            Stall("H6_14", "Media", True),
            Stall("H6_15", "Automation", False),
            Stall("H6_16", "Fasteners", False),
            Stall("H6_17", "Automation", False),
            Stall("H6_18", "Automation", False),
            Stall("H6_19", "Automation", False),
            Stall("H6_20", "Automation", False),
            Stall("H6_21", "Automation", False),
            Stall("H6_A", "Automation", False),
            Stall("H6_B", "Automation", False),
            Stall("H6_C", "Automation", False),
            Stall("H6_D", "Automation", False),
        ],
    ),
    "H7": Hall(
        "H7",
        "Tools",
        [
            Stall("H7_1", "Tools", False),
            Stall("H7_2", "Cutting", False),
            Stall("H7_3", "Tools", False),
            Stall("H7_4", "Fasteners", False),
            Stall("H7_5", "Tools", False),
            Stall("H7_6", "Media", True),
            Stall("H7_7", "Tools", False),
            Stall("H7_8", "Automation", False),
            Stall("H7_9", "Tools", False),
            Stall("H7_10", "Software", True),
            Stall("H7_11", "Tools", False),
            Stall("H7_12", "Pressing", False),
            Stall("H7_13", "Tools", False),
            Stall("H7_14", "Services", True),
            Stall("H7_15", "Tools", False),
            Stall("H7_16", "Lasers", False),
            Stall("H7_17", "Tools", False),
            Stall("H7_18", "Tools", False),
            Stall("H7_19", "Tools", False),
            Stall("H7_20", "Tools", False),
            Stall("H7_21", "Tools", False),
            Stall("H7_A", "Tools", False),
            Stall("H7_B", "Tools", False),
            Stall("H7_C", "Tools", False),
            Stall("H7_D", "Tools", False),
        ],
    ),
}

ROUTES = {
    "H1": [
        Route(
            "H1_R1",
            [
                "H1_1",
                "H1_2",
                "H1_A",
                "H1_3",
                "H1_4",
                "H1_5",
                "H1_C",
                "H1_6",
                "H1_7",
                "H1_8",
                "H1_9",
                "H1_10",
                "H1_11",
                "H1_12",
                "H1_13",
                "H1_14",
                "H1_15",
                "H1_16",
                "H1_D",
                "H1_17",
                "H1_18",
                "H1_19",
                "H1_20",
                "H1_21",
                "H1_B",
            ],
            0.15,
        ),
        Route(
            "H1_R2",
            [
                "H1_1",
                "H1_2",
                "H1_3",
                "H1_4",
                "H1_5",
                "H1_6",
                "H1_7",
                "H1_8",
                "H1_9",
                "H1_10",
                "H1_C",
                "H1_D",
                "H1_A",
                "H1_B",
            ],
            0.25,
        ),
        Route(
            "H1_R3",
            [
                "H1_A",
                "H1_C",
                "H1_11",
                "H1_13",
                "H1_13",
                "H1_14",
                "H1_15",
                "H1_16",
                "H1_D",
                "H1_17",
                "H1_18",
                "H1_19",
                "H1_20",
                "H1_B",
                "H1_21",
            ],
            0.25,
        ),
        Route(
            "H1_R4",
            ["H1_1", "H1_2", "H1_3", "H1_A", "H1_B", "H1_19", "H1_20", "H1_21"],
            0.35,
        ),
    ],
    "H2": [
        Route(
            "H2_R1",
            [
                "H2_1",
                "H2_2",
                "H2_A",
                "H2_3",
                "H2_4",
                "H2_5",
                "H2_C",
                "H2_6",
                "H2_7",
                "H2_8",
                "H2_9",
                "H2_10",
                "H2_11",
                "H2_12",
                "H2_13",
                "H2_14",
                "H2_15",
                "H2_16",
                "H2_D",
                "H2_17",
                "H2_18",
                "H2_19",
                "H2_20",
                "H2_21",
                "H2_B",
            ],
            0.15,
        ),
        Route(
            "H2_R2",
            [
                "H2_1",
                "H2_2",
                "H2_3",
                "H2_4",
                "H2_5",
                "H2_6",
                "H2_7",
                "H2_8",
                "H2_9",
                "H2_10",
                "H2_C",
                "H2_D",
                "H2_A",
                "H2_B",
            ],
            0.25,
        ),
        Route(
            "H2_R3",
            [
                "H2_A",
                "H2_C",
                "H2_11",
                "H2_13",
                "H2_13",
                "H2_14",
                "H2_15",
                "H2_16",
                "H2_D",
                "H2_17",
                "H2_18",
                "H2_19",
                "H2_20",
                "H2_B",
                "H2_21",
            ],
            0.25,
        ),
        Route(
            "H2_R4",
            ["H2_1", "H1_2", "H1_3", "H1_A", "H1_B", "H1_19", "H1_20", "H1_21"],
            0.35,
        ),
    ],
    "H3": [
        Route(
            "H3_R1",
            [
                "H3_1",
                "H3_2",
                "H3_A",
                "H3_3",
                "H3_4",
                "H3_5",
                "H3_C",
                "H3_6",
                "H3_7",
                "H3_8",
                "H3_9",
                "H3_10",
                "H3_11",
                "H3_12",
                "H3_13",
                "H3_14",
                "H3_15",
                "H3_16",
                "H3_D",
                "H3_17",
                "H3_18",
                "H3_19",
                "H3_20",
                "H3_21",
                "H3_B",
            ],
            0.15,
        ),
        Route(
            "H3_R2",
            [
                "H3_1",
                "H3_2",
                "H3_3",
                "H3_4",
                "H3_5",
                "H3_6",
                "H3_7",
                "H3_8",
                "H3_9",
                "H3_10",
                "H3_C",
                "H3_D",
                "H3_A",
                "H3_B",
            ],
            0.25,
        ),
        Route(
            "H3_R3",
            [
                "H3_A",
                "H3_C",
                "H3_11",
                "H3_13",
                "H3_13",
                "H3_14",
                "H3_15",
                "H3_16",
                "H3_D",
                "H3_17",
                "H3_18",
                "H3_19",
                "H3_20",
                "H3_B",
                "H3_21",
            ],
            0.25,
        ),
        Route(
            "H3_R4",
            ["H3_1", "H1_2", "H1_3", "H1_A", "H1_B", "H1_19", "H1_20", "H1_21"],
            0.35,
        ),
    ],
    "H4": [
        Route(
            "H4_R1",
            [
                "H4_1",
                "H4_2",
                "H4_A",
                "H4_3",
                "H4_4",
                "H4_5",
                "H4_C",
                "H4_6",
                "H4_7",
                "H4_8",
                "H4_9",
                "H4_10",
                "H4_11",
                "H4_12",
                "H4_13",
                "H4_14",
                "H4_15",
                "H4_16",
                "H4_D",
                "H4_17",
                "H4_18",
                "H4_19",
                "H4_20",
                "H4_21",
                "H4_B",
            ],
            0.15,
        ),
        Route(
            "H4_R2",
            [
                "H4_1",
                "H4_2",
                "H4_3",
                "H4_4",
                "H4_5",
                "H4_6",
                "H4_7",
                "H4_8",
                "H4_9",
                "H4_10",
                "H4_C",
                "H4_D",
                "H4_A",
                "H4_B",
            ],
            0.25,
        ),
        Route(
            "H4_R3",
            [
                "H4_A",
                "H4_C",
                "H4_11",
                "H4_13",
                "H4_13",
                "H4_14",
                "H4_15",
                "H4_16",
                "H4_D",
                "H4_17",
                "H4_18",
                "H4_19",
                "H4_20",
                "H4_B",
                "H4_21",
            ],
            0.25,
        ),
        Route(
            "H4_R4",
            ["H4_1", "H1_2", "H1_3", "H1_A", "H1_B", "H1_19", "H1_20", "H1_21"],
            0.35,
        ),
    ],
    "H5": [
        Route(
            "H5_R1",
            [
                "H5_1",
                "H5_2",
                "H5_A",
                "H5_3",
                "H5_4",
                "H5_5",
                "H5_C",
                "H5_6",
                "H5_7",
                "H5_8",
                "H5_9",
                "H5_10",
                "H5_11",
                "H5_12",
                "H5_13",
                "H5_14",
                "H5_15",
                "H5_16",
                "H5_D",
                "H5_17",
                "H5_18",
                "H5_19",
                "H5_20",
                "H5_21",
                "H5_B",
            ],
            0.15,
        ),
        Route(
            "H5_R2",
            [
                "H5_1",
                "H5_2",
                "H5_3",
                "H5_4",
                "H5_5",
                "H5_6",
                "H5_7",
                "H5_8",
                "H5_9",
                "H5_10",
                "H5_C",
                "H5_D",
                "H5_A",
                "H5_B",
            ],
            0.25,
        ),
        Route(
            "H5_R3",
            [
                "H5_A",
                "H5_C",
                "H5_11",
                "H5_13",
                "H5_13",
                "H5_14",
                "H5_15",
                "H5_16",
                "H5_D",
                "H5_17",
                "H5_18",
                "H5_19",
                "H5_20",
                "H5_B",
                "H5_21",
            ],
            0.25,
        ),
        Route(
            "H5_R4",
            ["H5_1", "H1_2", "H1_3", "H1_A", "H1_B", "H1_19", "H1_20", "H1_21"],
            0.35,
        ),
    ],
    "H6": [
        Route(
            "H6_R1",
            [
                "H6_1",
                "H6_2",
                "H6_A",
                "H6_3",
                "H6_4",
                "H6_5",
                "H6_C",
                "H6_6",
                "H6_7",
                "H6_8",
                "H6_9",
                "H6_10",
                "H6_11",
                "H6_12",
                "H6_13",
                "H6_14",
                "H6_15",
                "H6_16",
                "H6_D",
                "H6_17",
                "H6_18",
                "H6_19",
                "H6_20",
                "H6_21",
                "H6_B",
            ],
            0.15,
        ),
        Route(
            "H6_R2",
            [
                "H6_1",
                "H6_2",
                "H6_3",
                "H6_4",
                "H6_5",
                "H6_6",
                "H6_7",
                "H6_8",
                "H6_9",
                "H6_10",
                "H6_C",
                "H6_D",
                "H6_A",
                "H6_B",
            ],
            0.25,
        ),
        Route(
            "H6_R3",
            [
                "H6_A",
                "H6_C",
                "H6_11",
                "H6_13",
                "H6_13",
                "H6_14",
                "H6_15",
                "H6_16",
                "H6_D",
                "H6_17",
                "H6_18",
                "H6_19",
                "H6_20",
                "H6_B",
                "H6_21",
            ],
            0.25,
        ),
        Route(
            "H6_R4",
            ["H6_1", "H1_2", "H1_3", "H1_A", "H1_B", "H1_19", "H1_20", "H1_21"],
            0.35,
        ),
    ],
    "H7": [
        Route(
            "H7_R1",
            [
                "H7_1",
                "H7_2",
                "H7_A",
                "H7_3",
                "H7_4",
                "H7_5",
                "H7_C",
                "H7_6",
                "H7_7",
                "H7_8",
                "H7_9",
                "H7_10",
                "H7_11",
                "H7_12",
                "H7_13",
                "H7_14",
                "H7_15",
                "H7_16",
                "H7_D",
                "H7_17",
                "H7_18",
                "H7_19",
                "H7_20",
                "H7_21",
                "H7_B",
            ],
            0.15,
        ),
        Route(
            "H7_R2",
            [
                "H7_1",
                "H7_2",
                "H7_3",
                "H7_4",
                "H7_5",
                "H7_6",
                "H7_7",
                "H7_8",
                "H7_9",
                "H7_10",
                "H7_C",
                "H7_D",
                "H7_A",
                "H7_B",
            ],
            0.25,
        ),
        Route(
            "H7_R3",
            [
                "H7_A",
                "H7_C",
                "H7_11",
                "H7_13",
                "H7_13",
                "H7_14",
                "H7_15",
                "H7_16",
                "H7_D",
                "H7_17",
                "H7_18",
                "H7_19",
                "H7_20",
                "H7_B",
                "H7_21",
            ],
            0.25,
        ),
        Route(
            "H7_R4",
            ["H7_1", "H1_2", "H1_3", "H1_A", "H1_B", "H1_19", "H1_20", "H1_21"],
            0.35,
        ),
    ],
}
